"""empty message

Revision ID: 054253a20fde
Revises: fb01026f520b
Create Date: 2016-06-10 15:15:09.173141

"""

# revision identifiers, used by Alembic.
revision = '054253a20fde'
down_revision = 'fb01026f520b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkclicks', sa.Column('userid', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkclicks', 'userid')
    ### end Alembic commands ###
