"""empty message

Revision ID: 252bc93cfe2b
Revises: 501c197c6f37
Create Date: 2016-06-13 17:24:12.116597

"""

# revision identifiers, used by Alembic.
revision = '252bc93cfe2b'
down_revision = '501c197c6f37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactions')
    ### end Alembic commands ###
