"""Added UserCluster table

Revision ID: 3fed71762d8c
Revises: a8de15a59b64
Create Date: 2016-07-08 10:19:38.615722

"""

# revision identifiers, used by Alembic.
revision = '3fed71762d8c'
down_revision = 'a8de15a59b64'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cluster', postgresql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_clusters')
    ### end Alembic commands ###
