"""empty message

Revision ID: 3ff4cf5c5df3
Revises: 951e7c1ecbc2
Create Date: 2016-06-10 11:05:36.156758

"""

# revision identifiers, used by Alembic.
revision = '3ff4cf5c5df3'
down_revision = '951e7c1ecbc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkclicks', sa.Column('userid', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkclicks', 'userid')
    ### end Alembic commands ###
