"""Adding json graph table

Revision ID: 490cf9604239
Revises: bb58d6b21e66
Create Date: 2016-06-27 12:43:01.962598

"""

# revision identifiers, used by Alembic.
revision = '490cf9604239'
down_revision = 'bb58d6b21e66'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('userid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphs')
    ### end Alembic commands ###
