"""Added unique constraint to userid

Revision ID: 57917b0afd7d
Revises: 411dba076aec
Create Date: 2016-08-03 10:07:11.560880

"""

# revision identifiers, used by Alembic.
revision = '57917b0afd7d'
down_revision = '411dba076aec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cluster_hierarchy', ['userid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cluster_hierarchy', type_='unique')
    ### end Alembic commands ###
