"""empty message

Revision ID: 6103a4e20c07
Revises: None
Create Date: 2016-06-06 15:00:12.140857

"""

# revision identifiers, used by Alembic.
revision = '6103a4e20c07'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagevisits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionid', sa.Integer(), nullable=True),
    sa.Column('tabid', sa.Integer(), nullable=True),
    sa.Column('windowid', sa.Integer(), nullable=True),
    sa.Column('srcid', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('transition', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagevisits')
    ### end Alembic commands ###
