"""empty message

Revision ID: 951e7c1ecbc2
Revises: e8a10ccc977b
Create Date: 2016-06-09 16:35:41.575203

"""

# revision identifiers, used by Alembic.
revision = '951e7c1ecbc2'
down_revision = 'e8a10ccc977b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkclicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(), nullable=True),
    sa.Column('dest', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkclicks')
    ### end Alembic commands ###
