"""Added exclusions column to user clusters

Revision ID: 9dad42b3d94f
Revises: 57917b0afd7d
Create Date: 2016-08-12 15:25:00.624227

"""

# revision identifiers, used by Alembic.
revision = '9dad42b3d94f'
down_revision = '57917b0afd7d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_clusters', sa.Column('exclusions', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_clusters', 'exclusions')
    ### end Alembic commands ###
