"""Unique constraint for user clusters

Revision ID: a6acf65c378d
Revises: 3fed71762d8c
Create Date: 2016-07-15 17:16:39.001494

"""

# revision identifiers, used by Alembic.
revision = 'a6acf65c378d'
down_revision = '3fed71762d8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('u_name', 'user_clusters', ['userid', 'name'])
    op.create_unique_constraint(None, 'user_clusters', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_clusters', type_='unique')
    op.drop_constraint('u_name', 'user_clusters', type_='unique')
    ### end Alembic commands ###
