"""empty message

Revision ID: bb58d6b21e66
Revises: 501c197c6f37
Create Date: 2016-06-15 08:33:28.610544

"""

# revision identifiers, used by Alembic.
revision = 'bb58d6b21e66'
down_revision = '501c197c6f37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('target', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'target')
    ### end Alembic commands ###
